"""Export engine for meeting summaries and action items.

Supports Markdown, JSON, and PDF output formats.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"
OUTPUT_DIR = Path(__file__).parent.parent / "output"


class Exporter:
    """Exports meeting summaries to Markdown, JSON, or PDF."""

    def __init__(self, output_dir: str | Path | None = None):
        self.output_dir = Path(output_dir) if output_dir else OUTPUT_DIR
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export_data(
        self,
        title: str,
        summary: str,
        action_items: List[Dict[str, Any]],
        key_topics: Optional[List[str]] = None,
        decisions: Optional[List[str]] = None,
        open_questions: Optional[List[str]] = None,
        fmt: str = "markdown",
        date: str = "",
    ) -> Path:
        """Export raw dictionary summary data to file."""
        fmt = fmt.lower().strip()
        data = {
            "title": title or "Meeting Summary",
            "date": date or datetime.now().strftime("%Y-%m-%d"),
            "summary": summary,
            "key_topics": key_topics or [],
            "decisions": decisions or [],
            "open_questions": open_questions or [],
            "action_items": action_items,
        }

        if fmt == "json":
            return self.to_json(data)
        elif fmt == "pdf":
            return self.to_pdf(data)
        else:
            return self.to_markdown(data)

    def to_markdown(self, data: Dict[str, Any]) -> Path:
        """Export summary data to a clean Markdown document."""
        title = data.get("title", "Meeting Summary")
        filename = self._generate_filename(title, ".md")
        filepath = self.output_dir / filename

        lines = [
            f"# 📋 {title}",
            "",
            f"**Date:** {data.get('date', '')}  ",
            "",
            "---",
            "",
            "## 📝 Summary",
            "",
            data.get("summary", ""),
            "",
        ]

        if data.get("key_topics"):
            lines.append("## 🎯 Key Topics")
            lines.append("")
            for topic in data["key_topics"]:
                lines.append(f"- {topic}")
            lines.append("")

        if data.get("decisions"):
            lines.append("## ✅ Decisions Made")
            lines.append("")
            for dec in data["decisions"]:
                lines.append(f"- {dec}")
            lines.append("")

        if data.get("action_items"):
            lines.append("## 🚀 Action Items")
            lines.append("")
            lines.append("| # | Task | Owner | Priority | Due Date |")
            lines.append("|---|------|-------|----------|----------|")
            for idx, item in enumerate(data["action_items"], 1):
                prio = item.get("priority", "medium").upper()
                emoji = "🔴" if prio == "HIGH" else ("🟡" if prio == "MEDIUM" else "🟢")
                owner = item.get("assignee") or item.get("owner") or "Unassigned"
                task = item.get("task") or item.get("description") or ""
                due = item.get("due_date") or item.get("due") or "—"
                lines.append(f"| {idx} | {task} | {owner} | {emoji} {prio} | {due} |")
            lines.append("")

        if data.get("open_questions"):
            lines.append("## ❓ Open Questions")
            lines.append("")
            for q in data["open_questions"]:
                lines.append(f"- {q}")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by AI Meeting Intelligence Suite*")

        filepath.write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Markdown exported: {filepath}")
        return filepath

    def to_json(self, data: Dict[str, Any]) -> Path:
        """Export summary data to JSON."""
        title = data.get("title", "Meeting Summary")
        filename = self._generate_filename(title, ".json")
        filepath = self.output_dir / filename

        filepath.write_text(
            json.dumps(data, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        logger.info(f"JSON exported: {filepath}")
        return filepath

    def to_pdf(self, data: Dict[str, Any]) -> Path:
        """Export summary data to styled PDF."""
        title = data.get("title", "Meeting Summary")
        filename = self._generate_filename(title, ".pdf")
        filepath = self.output_dir / filename

        html_content = self._render_html(data)

        try:
            from weasyprint import HTML
            HTML(string=html_content).write_pdf(str(filepath))
            logger.info(f"PDF exported via WeasyPrint: {filepath}")
            return filepath
        except Exception as e:
            logger.warning(f"WeasyPrint PDF export failed ({e}), rendering HTML fallback file.")
            html_filepath = self.output_dir / self._generate_filename(title, ".html")
            html_filepath.write_text(html_content, encoding="utf-8")
            return html_filepath

    def _render_html(self, data: Dict[str, Any]) -> str:
        """Render HTML string for PDF/HTML output."""
        action_rows = ""
        for idx, a in enumerate(data.get("action_items", []), 1):
            owner = a.get("assignee") or a.get("owner") or "Unassigned"
            task = a.get("task") or a.get("description") or ""
            due = a.get("due_date") or a.get("due") or "—"
            prio = (a.get("priority") or "medium").upper()
            action_rows += f"<tr><td>{idx}</td><td>{task}</td><td>{owner}</td><td>{prio}</td><td>{due}</td></tr>\n"

        decision_items = "".join(f"<li>{d}</li>" for d in data.get("decisions", []))

        return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{data.get('title')}</title>
<style>
body {{ font-family: 'Segoe UI', Helvetica, Arial, sans-serif; margin: 40px; color: #1e293b; background: #fff; }}
h1 {{ color: #0f172a; border-bottom: 3px solid #2563eb; padding-bottom: 10px; font-size: 24px; }}
h2 {{ color: #1e40af; margin-top: 25px; font-size: 18px; }}
table {{ border-collapse: collapse; width: 100%; margin: 15px 0; font-size: 14px; }}
th, td {{ border: 1px solid #cbd5e1; padding: 10px; text-align: left; }}
th {{ background: #f1f5f9; color: #0f172a; font-weight: 600; }}
tr:nth-child(even) {{ background: #f8fafc; }}
.meta {{ color: #64748b; font-size: 13px; margin-bottom: 20px; }}
.summary-box {{ background: #eff6ff; border-left: 4px solid #3b82f6; padding: 15px; border-radius: 4px; }}
</style>
</head>
<body>
<h1>📋 {data.get('title')}</h1>
<p class="meta"><strong>Date:</strong> {data.get('date')}</p>

<h2>📝 Summary</h2>
<div class="summary-box">{data.get('summary')}</div>

{"<h2>✅ Key Decisions</h2><ul>" + decision_items + "</ul>" if decision_items else ""}

<h2>🚀 Action Items</h2>
<table>
<tr><th>#</th><th>Task</th><th>Owner</th><th>Priority</th><th>Due</th></tr>
{action_rows}
</table>

<hr style="margin-top:40px; border:none; border-top:1px solid #e2e8f0;">
<p style="font-size:12px; color:#94a3b8; text-align:center;">Generated by AI Meeting Intelligence Suite</p>
</body>
</html>"""

    @staticmethod
    def _generate_filename(title: str, extension: str) -> str:
        clean = "".join(c if c.isalnum() or c == " " else "" for c in title)
        clean = clean.strip().replace(" ", "_")[:40].lower()
        date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"meeting_{date_str}_{clean}{extension}"
