"""add_features_v2

Revision ID: 504236485ad9
Revises: c76154c729e6
Create Date: 2026-05-31 21:56:10.251236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '504236485ad9'
down_revision: Union[str, None] = 'c76154c729e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension (required for Vector column type)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('email_send_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('send_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_send_logs_meeting_id'), 'email_send_logs', ['meeting_id'], unique=False)
    op.create_table('embedding_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('chunk_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_chunks_meeting_id'), 'embedding_chunks', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_embedding_chunks_user_id'), 'embedding_chunks', ['user_id'], unique=False)
    op.create_index('ix_embedding_chunks_user_meeting', 'embedding_chunks', ['user_id', 'meeting_id'], unique=False)
    op.create_table('meeting_speakers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_speakers_meeting_id'), 'meeting_speakers', ['meeting_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('speaker_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['meeting_speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_meeting_id'), 'transcript_segments', ['meeting_id'], unique=False)
    op.create_index('ix_transcript_segments_meeting_seq', 'transcript_segments', ['meeting_id', 'sequence_order'], unique=False)
    op.add_column('action_items', sa.Column('status', sa.String(), nullable=True))
    op.add_column('follow_up_emails', sa.Column('is_sent', sa.Boolean(), nullable=True))
    op.add_column('follow_up_emails', sa.Column('sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_up_emails', 'sent_at')
    op.drop_column('follow_up_emails', 'is_sent')
    op.drop_column('action_items', 'status')
    op.drop_index('ix_transcript_segments_meeting_seq', table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_meeting_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_meeting_speakers_meeting_id'), table_name='meeting_speakers')
    op.drop_table('meeting_speakers')
    op.drop_index('ix_embedding_chunks_user_meeting', table_name='embedding_chunks')
    op.drop_index(op.f('ix_embedding_chunks_user_id'), table_name='embedding_chunks')
    op.drop_index(op.f('ix_embedding_chunks_meeting_id'), table_name='embedding_chunks')
    op.drop_table('embedding_chunks')
    op.drop_index(op.f('ix_email_send_logs_meeting_id'), table_name='email_send_logs')
    op.drop_table('email_send_logs')
    op.drop_table('slack_settings')
    # ### end Alembic commands ###
